name: rustconn
base: core24
version: '0.6.3'
summary: Modern connection manager for Linux
description: |
  RustConn is a GTK4/libadwaita connection manager supporting SSH, RDP, VNC, 
  SPICE protocols and Zero Trust integrations (AWS SSM, GCP IAP, Azure, etc.)
  
  Features:
  - Embedded SSH terminals with split view
  - Connection organization via groups and tags
  - Import/Export: Remmina, Asbru-CM, SSH config, Ansible, Royal TS, MobaXterm
  - Credential backends: libsecret, KeePassXC, Bitwarden CLI
  - Session logging, command snippets, cluster commands, Wake-on-LAN

grade: stable
confinement: strict
icon: rustconn/assets/icons/hicolor/256x256/apps/io.github.totoshko88.RustConn.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  rustconn:
    command: bin/rustconn-wrapper
    desktop: usr/share/applications/io.github.totoshko88.RustConn.desktop
    common-id: io.github.totoshko88.RustConn
    plugs:
      - home
      - network
      - network-bind
      - ssh-keys
      - gpg-keys
      - password-manager-service
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/usr/share/drirc.d
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/glib-2.0/schemas:
    bind: $SNAP/usr/share/glib-2.0/schemas

parts:
  rustconn:
    plugin: rust
    source: .
    rust-channel: "1.87"
    rust-path: [rustconn]
    rust-use-global-lto: true
    build-packages:
      - libgtk-4-dev
      - libadwaita-1-dev
      - libvte-2.91-gtk4-dev
      - libssl-dev
      - libasound2-dev
      - pkg-config
      - clang
      - cmake
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libvte-2.91-gtk4-0
      - libasound2t64
      - libssl3t64
      - libgl1
      - libglx-mesa0
      - libdrm2
      - libgbm1
      - libegl1
      - libwayland-client0
      - libwayland-egl1
      - libxkbcommon0
      - openssh-client
    organize:
      bin/rustconn: usr/bin/rustconn
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp rustconn/assets/io.github.totoshko88.RustConn.desktop $CRAFT_PART_INSTALL/usr/share/applications/
      cp -r rustconn/assets/icons/hicolor $CRAFT_PART_INSTALL/usr/share/icons/
      cat > $CRAFT_PART_INSTALL/bin/rustconn-wrapper << 'WRAPPER'
      #!/bin/bash
      export GTK_USE_PORTAL=1
      export GDK_BACKEND=wayland,x11
      export GDK_GL=gles
      export GSK_RENDERER=gl
      export LD_LIBRARY_PATH=$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$LD_LIBRARY_PATH
      export GI_TYPELIB_PATH=$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      export XDG_DATA_DIRS=$SNAP/usr/share:$XDG_DATA_DIRS
      export GTK_PATH=$SNAP/usr/lib/x86_64-linux-gnu/gtk-4.0
      export GDK_PIXBUF_MODULE_FILE=$SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
      exec "$SNAP/usr/bin/rustconn" "$@"
      WRAPPER
      chmod +x $CRAFT_PART_INSTALL/bin/rustconn-wrapper
